default_context:
  project_name: 'myproject'
  project_slug: 'mpj'
  domain_main: 'mpj.com'
  domain_staging: 'stag.mpj.com'
  docker_swarm_stack_name_main: 'mpj-com'
  docker_swarm_stack_name_staging: 'stag-mpj-com'
  secret_key: 'skey1'
  first_superuser: 'admin@mpj.com'
  first_superuser_password: 'admin'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.mpj.com", "https://stag.mpj.com", "https://mpj.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@mpj.com'
  mysql_user": "root1",
  mysql_password": "root",
  mysql_database": "mpj",
  mysql_root_password": "root",
  traefik_constraint_tag: 'mpj.com'
  traefik_constraint_tag_staging: 'stag.mpj.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:admin'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
